#!/usr/bin/env bash
# 一键部署:自动 export → 提交 → 推送 → 服务器 pull → import → 重启
# 用法:./deploy.sh
#
# 智能跳过:如果 client/server/shared/assets/... 都没改过,跳过 export 步骤,
# 整个流程几秒钟。改了任何源文件就自动重新 export(约 30-60 秒)。

set -e

cd "$(dirname "$0")"

# ---- 0. 并发锁(防多 session 同时 deploy 互相踩工作树) ----
# 多个 session 并发 deploy 会争 .godot/exported、git index、VPS 工作树,
# 产物可能不对。用原子 mkdir 锁(macOS 没有 flock(1))。带 stale 检测:
# 持锁进程若已死(kill -9 没触发 trap 清理),自动抢锁继续。
LOCK_DIR=".deploy.lock"
if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  OTHER_PID="$(cat "$LOCK_DIR/pid" 2>/dev/null || echo '?')"
  if [ "$OTHER_PID" != "?" ] && kill -0 "$OTHER_PID" 2>/dev/null; then
    echo "⛔ 已有 deploy 在跑 (PID $OTHER_PID)。等它结束,或先 kill 再试。"
    echo "   (这正是之前 13 个 deploy 并发卡死的场景,现在被锁拦下了)"
    exit 1
  fi
  echo "⚠️  发现残留锁 (PID $OTHER_PID 已不在),抢锁继续。"
  rm -rf "$LOCK_DIR"; mkdir "$LOCK_DIR"
fi
echo $$ > "$LOCK_DIR/pid"
trap 'rm -rf "$LOCK_DIR"' EXIT

# ---- SSH keepalive(防半开死连接) ----
# 之前 ssh import 步骤会变成半开连接:VPS 端早跑完,本地 ssh 收不到关闭信号
# 永远挂着,deploy 僵死 1+ 小时。ServerAliveInterval 让本地每 15s 探一次,
# 连续 4 次(60s)无响应就主动断开,deploy 才能 set -e 退出 + 释放锁。
SSH_OPTS=(-o ConnectTimeout=15 -o ServerAliveInterval=15 -o ServerAliveCountMax=4)

# ---- 配置(改服务器时改这里) ----
SERVER_HOST="${PVP_SERVER_HOST:-root@207.148.98.206}"
SERVER_PATH="${PVP_SERVER_PATH:-/opt/games/godot-pvp}"
SERVICE_NAME="godot-pvp-game"
PUBLIC_URL="https://game.boobank.com/godot-pvp/"

# ---- 1. 找 Godot 二进制 ----
if [ -n "$GODOT_BIN" ] && [ -x "$GODOT_BIN" ]; then
  : # 用环境变量
else
  CANDIDATES=(
    "/Applications/Godot.app/Contents/MacOS/Godot"
    "$HOME/Applications/Godot.app/Contents/MacOS/Godot"
    "$HOME/Downloads/Godot.app/Contents/MacOS/Godot"
    "$HOME/Desktop/Godot.app/Contents/MacOS/Godot"
  )
  GODOT_BIN=""
  for c in "${CANDIDATES[@]}"; do
    if [ -x "$c" ]; then GODOT_BIN="$c"; break; fi
  done
  if [ -z "$GODOT_BIN" ]; then
    APP=$(mdfind "kMDItemFSName == 'Godot.app'" 2>/dev/null | head -1)
    [ -n "$APP" ] && [ -x "$APP/Contents/MacOS/Godot" ] && GODOT_BIN="$APP/Contents/MacOS/Godot"
  fi
fi

if [ -z "$GODOT_BIN" ] || [ ! -x "$GODOT_BIN" ]; then
  echo "❌ Godot 找不到。请装到 /Applications 或 ~/Downloads,或 export GODOT_BIN=/path/to/Godot"
  exit 1
fi

# ---- 2. 判断需不需要重新 export ----
NEED_EXPORT=0
REASON=""
if [ ! -f docs/index.pck ] || [ ! -f docs/index.wasm ]; then
  NEED_EXPORT=1
  REASON="docs/ 不完整"
else
  # 找比 docs/index.pck 新的源文件(说明改过代码 / 资源)
  # 加 export_presets.cfg 是因为我们改过几次 exclude_filter / extensions_support,
  # 这种纯 export config 的改动 Godot 不会自动重新打包,必须靠 deploy 这里强制触发。
  NEWER=$(find client server shared assets addons project.godot server.json export_presets.cfg \
    -newer docs/index.pck 2>/dev/null | head -3)
  if [ -n "$NEWER" ]; then
    NEED_EXPORT=1
    REASON="检测到源文件变更:"$'\n'"$NEWER"
  fi
fi

# ---- 3. 自动 export(如果需要) ----
if [ "$NEED_EXPORT" = "1" ]; then
  echo "📦 需要重新 export:$REASON"
  echo "→ 清理旧编译缓存..."
  # 清掉 .godot/exported,否则 Godot 可能复用旧的 .gdc 编译产物
  rm -rf .godot/exported

  # 烧版本号到 build_info.gd,主菜单读它显示在右下角。
  # 用户(尤其 Safari 用户)硬刷后看版本号就能确认是否拿到新版本。
  BUILD_VER="$(date '+%Y-%m-%d %H:%M') · $(git rev-parse --short HEAD)"
  echo "→ 烙版本号:$BUILD_VER"
  cat > client/scripts/build_info.gd <<EOF
class_name BuildInfo
extends RefCounted
## Auto-generated by deploy.sh. DON'T hand-edit.
const VERSION := "$BUILD_VER"
EOF

  echo "→ Godot 导出 Web 构建(约 30-60 秒)..."
  "$GODOT_BIN" --headless --path . --export-release "Web" docs/index.html 2>&1 | tail -5

  # 清掉 docs/ 里的 .import 编辑器残留(它们只是元数据,不该 commit)
  find docs -name "*.import" -delete 2>/dev/null || true
  # 同步 server.json 到 docs/(Caddy 同源 fetch 用)
  cp server.json docs/server.json

  # 给 index.html 里引用的 splash/icon png 加版本号 ?v=<hash>。
  # 原因:这些 png 走 Cloudflare 边缘缓存(默认对图片 max-age 4h,还覆盖
  # origin 的 Cache-Control),改了 boot splash 也看到旧机器人。index.html
  # 本身是 no-cache(Caddy header,CF 不缓存 html),所以浏览器每次拿新 html,
  # 只要 png 的 URL 带新 hash,CF 就 MISS → 拿到新图。无需手动 purge CF。
  BUST="$(git rev-parse --short HEAD)"
  sed -i '' \
    -e "s|src=\"index.png\"|src=\"index.png?v=$BUST\"|g" \
    -e "s|href=\"index.icon.png\"|href=\"index.icon.png?v=$BUST\"|g" \
    -e "s|href=\"index.apple-touch-icon.png\"|href=\"index.apple-touch-icon.png?v=$BUST\"|g" \
    docs/index.html
  echo "→ splash/icon 加缓存版本号 ?v=$BUST"

  # 关键性能注入:封顶渲染 DPR(设备感知)。Godot web canvasResizePolicy=2 把
  # canvas 渲染到 clientWidth × devicePixelRatio。实测铁证:5K×DPR2 = 1290 万
  # 像素的巨型 canvas,浏览器按显示器 60Hz 合成它就把 GPU 打满 → 风扇狂转
  # (缩小窗口画布 → Chrome 渲染进程 83%→6%,与 Godot 帧率无关)。
  #   · 手机(DPR3,小屏):cap=2 → 文字清晰(cap=1 会糊,用户验证过)
  #   · 桌面高分屏(5K Mac,DPR2):cap=1.5 → 画布像素砍 44%、文字仍 165ppi 锐利
  # 手机端不受影响。这是唯一对风扇有效的杠杆(降帧率实测无效)。
  python3 - <<'PYEOF'
import re
html = open("docs/index.html", encoding="utf-8").read()
snippet = ('<script>/*__dpr_cap__ cap render DPR: touch(phone)=2 crisp text, '
           'desktop HiDPI=1.5 to cut the 5K canvas fill/compositing that pegs '
           'the GPU (the fan). Fps does NOT help — compositing is per-pixel @60Hz*/'
           '(function(){var touch=("ontouchstart" in window)||(navigator.maxTouchPoints>0);'
           'var cap=touch?2:1.5;try{var d=Math.min(window.devicePixelRatio||1,cap);'
           'Object.defineProperty(window,"devicePixelRatio",'
           '{configurable:true,get:function(){return d;}});}catch(e){}})();</script>')
# 幂等:已注入则整段替换为最新版(升级旧的 cap=2 全局版 → 设备感知版)
if '/*__dpr_cap__' in html:
    html2 = re.sub(r'<script>/\*__dpr_cap__.*?</script>', snippet, html, count=1, flags=re.S)
    if html2 != html:
        open("docs/index.html","w",encoding="utf-8").write(html2)
        print("→ DPR cap 升级到设备感知(桌面 1.5 / 手机 2)")
    else:
        print("→ DPR cap 已是设备感知版,跳过")
else:
    html = html.replace("<head>", "<head>\n" + snippet, 1)
    open("docs/index.html","w",encoding="utf-8").write(html)
    print("→ 注入 DPR cap(桌面 1.5 / 手机 2)")
PYEOF

  # 注入战斗主题的加载页动画(web/loading_overlay.html → 在 </body> 前)。
  # canvas 粒子/曳光弹 + 雷达扫描 + logo 辉光 + 战术边框,纯增强不碰 Godot init。
  if [ -f web/loading_overlay.html ]; then
    python3 - <<'PYEOF'
import io
html = open("docs/index.html", encoding="utf-8").read()
overlay = open("web/loading_overlay.html", encoding="utf-8").read()
if "db-fx" not in html:   # idempotent
    html = html.replace("</body>", overlay + "\n</body>", 1)
    open("docs/index.html","w",encoding="utf-8").write(html)
    print("→ 注入加载页动画 overlay")
else:
    print("→ 加载页动画已存在,跳过")
PYEOF
  fi

  echo "✓ Export 完成"
  echo ""
else
  echo "✓ docs/ 已是最新,跳过 export"
  echo ""
fi

# ---- 3.5 brotli 预压缩 pck + wasm 给 Caddy precompressed 用 ----
# Caddy 的 file_server.precompressed 在客户端 Accept-Encoding: br 时优先
# serve `<file>.br`。关键:.br 必须和原始文件严格匹配 —— 否则浏览器解压
# 出截断/错版 wasm,报 "section extends past end of module",游戏加载死。
# 之前 VPS 端单独 brotli 会和 rsync 的原始文件错位(并发 deploy / 时序),
# 导致 .br 是旧 wasm 压的。改成:本地从同一份 export 压好 .br,连同原始
# 文件一起 rsync(见步骤 6,不再 --exclude .br),保证 raw 和 .br 永远一致。
if command -v brotli >/dev/null 2>&1; then
  echo "→ 本地预压缩 pck + wasm (brotli q11)..."
  brotli -q 11 -f docs/index.pck -o docs/index.pck.br
  brotli -q 11 -f docs/index.wasm -o docs/index.wasm.br
  ls -lh docs/index.pck.br docs/index.wasm.br | awk '{printf "  %s  %s\n", $5, $9}'
fi

# ---- 4. git 检查 + commit(只提交代码,不提交 docs/ 构建产物) ----
# docs/ 已 .gitignore —— web 构建用 rsync 直传 VPS(见步骤 6),不进 git,
# 避免每次 Build 把 28MB 的 pck 灌进仓库历史。
if [ ! -d .git ]; then
  echo "⚠️  这个项目还没用 git 初始化。"
  exit 1
fi

git add export_presets.cfg server.json .gitignore client/scripts/build_info.gd 2>/dev/null || true
if git diff --cached --quiet; then
  echo "(代码无变化,跳过 commit)"
else
  git commit -m "Build $(date '+%Y-%m-%d %H:%M')"
fi

# ---- 5. 推代码到 GitHub ----
echo ""
echo "→ 推送代码到 GitHub..."
git push

# ---- 6. 部署到服务器 ----
# (a) VPS 拉代码(DS 用)。
# (b) rsync web 构建 + 匹配的 .br 一起传(不再 --exclude .br):本地从同一份
#     export 压的 .br 和原始文件严格一致,避免 VPS 端单独 brotli 错位导致
#     wasm 截断("section extends past end of module" 加载死)。
# (c) import + 重启 DS(不再 VPS 重压 .br)。
echo ""
echo "→ (a) VPS 拉代码 ..."
ssh "${SSH_OPTS[@]}" "$SERVER_HOST" "cd '$SERVER_PATH' && git pull --rebase 2>&1 | tail -2"

echo "→ (b) rsync web 构建(含匹配的 .br) → VPS:docs/ ..."
rsync -az -e "ssh ${SSH_OPTS[*]}" docs/ "$SERVER_HOST:$SERVER_PATH/docs/"

echo "→ (c) VPS import + 重启 ..."
ssh "${SSH_OPTS[@]}" "$SERVER_HOST" "cd '$SERVER_PATH' \
  && godot --headless --path . --import 2>&1 | tail -3 \
  && sudo systemctl restart $SERVICE_NAME"

# ---- 7. done ----
echo ""
echo "✅ 部署完成,立即生效:"
echo "   $PUBLIC_URL"
echo "   (玩家硬刷新 Cmd/Ctrl+Shift+R 看新版本)"
